name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Pring geeting
        run:  echo "hello enin"
      - name: Pring bye
        run: echo "bye"
